# Generated by Django 2.1.4 on 2019-01-06 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('reply_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='EventPolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventPolls',
            },
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Meetings',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('event_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_API.EventPolls')),
            ],
            options={
                'db_table': 'Options',
            },
        ),
        migrations.CreateModel(
            name='ParticipantsVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Only_if_neccessary')], default=0)),
                ('event_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_API.EventPolls')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_API.Options')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ParticipantsVotes',
            },
        ),
        migrations.CreateModel(
            name='Participates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_API.Meetings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Participates',
            },
        ),
        migrations.CreateModel(
            name='PeriodicEventPolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('event_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_API.EventPolls')),
            ],
            options={
                'db_table': 'PeriodicEventPolls',
            },
        ),
        migrations.AddField(
            model_name='eventpolls',
            name='finalized_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_API.Options'),
        ),
        migrations.AddField(
            model_name='comments',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_API.Options'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
